In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

%matplotlib inline

In [ ]:
#1. Buatlah sebuah Matriks berukuran 5x5 dengan elemen random. Kemudian dari elemen yang dihasilkan perlihatkan nilai maksimum, nilai minimum dan
#elemen matriks yang di konstruksi.
matriks = np.random.randint(0, 100, size=(5, 5))

print("=== MATRIKS 5x5 ===")
print(matriks)

# Mencari nilai maksimum dan minimum
nilai_max = np.max(matriks)
nilai_min = np.min(matriks)

print(f"\nNilai Maksimum: {nilai_max}")
print(f"Nilai Minimum: {nilai_min}")

print("\nElemen-elemen matriks:")
print(matriks.flatten())

=== MATRIKS 5x5 ===
[[40 21 38 65 55]
 [ 5  8  6 58 61]
 [10 14 35 69 64]
 [52 26 63 60 56]
 [43 69  0 93 70]]

Nilai Maksimum: 93
Nilai Minimum: 0

Elemen-elemen matriks:
[40 21 38 65 55  5  8  6 58 61 10 14 35 69 64 52 26 63 60 56 43 69  0 93
 70]
